### ISSUE TITLE
As a meeting manager I want to schedule the messages to be shown on every single display.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.epaper.webapp#36] opened 2021-11-03 14:32 UTC

**Comment by SaimonasFOS** [comment] 2021-11-30 15:08
Possible duplicate of https://github.com/noi-techpark/it.bz.opendatahub.epaper.playground/issues/6 ? If not, then what is the difference between this task and another one?

**Closed as completed** 2021-12-02 10:09 UTC
Labels: duplicate, prj:epaper
